import type { PatternKey } from '../../data/patterns';
import type { PatternPreset, PatternVisualizerState } from './types';

export const PATTERN_PRESETS: Record<PatternKey, PatternPreset[]> = {
  hash_set: [
    {
      id: 'dup_early',
      label: 'Duplicate appears early',
      description: 'A repeated value appears near the front, so HashSet can stop early.',
      numsInput: '2,7,11,7,3,11',
    },
    {
      id: 'all_unique',
      label: 'All unique values',
      description: 'No duplicates exist, so the full list is scanned and result is null.',
      numsInput: '1,2,3,4,5,6',
    },
    {
      id: 'neg_zero_dup',
      label: 'Negative/zero with duplicate',
      description: 'Duplicate detection works the same with negatives and zero.',
      numsInput: '-3,0,4,-3,9,12',
    },
  ],
  hash_map: [
    {
      id: 'freq_mixed',
      label: 'Mixed frequencies',
      description: 'Some values appear once, some multiple times, so map counts diverge.',
      numsInput: '1,1,2,3,3,3,4',
    },
    {
      id: 'all_same',
      label: 'Single repeated value',
      description: 'One key accumulates all counts.',
      numsInput: '5,5,5,5,5',
    },
    {
      id: 'with_negatives',
      label: 'Includes negatives',
      description: 'Counts across positive, negative, and zero values.',
      numsInput: '4,-1,4,0,-1,4,2',
    },
  ],
  two_pointers: [
    {
      id: 'pair_exists',
      label: 'Pair exists',
      description: 'Sorted list contains a valid pair; pointers converge to match.',
      numsInput: '1,2,3,4,6,8',
      target: 10,
    },
    {
      id: 'no_pair',
      label: 'No pair matches target',
      description: 'No two values hit target, so pointers cross.',
      numsInput: '1,3,5,7,9',
      target: 2,
    },
    {
      id: 'duplicate_pair',
      label: 'Uses duplicate values',
      description: 'Pair can be formed with duplicate numbers.',
      numsInput: '1,2,2,3,4,6',
      target: 4,
    },
  ],
  sliding_window: [
    {
      id: 'window_grows',
      label: 'Window expands and shrinks',
      description: 'Running sum exceeds k repeatedly, forcing shrink steps.',
      numsInput: '2,1,3,2,1,1,1',
      windowK: 5,
    },
    {
      id: 'tight_limit',
      label: 'Tight limit',
      description: 'Small threshold causes frequent shrinking.',
      numsInput: '4,4,1,1,1',
      windowK: 4,
    },
    {
      id: 'none_valid',
      label: 'No valid window',
      description: 'Every value is larger than k, so best stays 0.',
      numsInput: '7,8,9',
      windowK: 5,
    },
  ],
  stack: [
    {
      id: 'valid_nested',
      label: 'Valid nested brackets',
      description: 'Properly nested and balanced symbols.',
      stackInput: '({[]})[]',
    },
    {
      id: 'mismatch',
      label: 'Mismatch example',
      description: 'Closing order is wrong, so mismatch occurs.',
      stackInput: '([)]',
    },
    {
      id: 'unfinished',
      label: 'Unfinished open brackets',
      description: 'Scan ends with leftover open symbols.',
      stackInput: '(([]',
    },
  ],
  bfs: [
    {
      id: 'open_grid',
      label: 'Reachable open grid',
      description: 'Most cells are reachable; queue grows by layers.',
      rows: 5,
      cols: 6,
      startR: 0,
      startC: 0,
      blockedInput: '1-1,1-2,3-4',
    },
    {
      id: 'narrow_paths',
      label: 'Narrow paths',
      description: 'Walls create corridors and constrained frontier expansion.',
      rows: 5,
      cols: 5,
      startR: 0,
      startC: 0,
      blockedInput: '0-2,1-2,2-2,3-1,3-3',
    },
    {
      id: 'blocked_start',
      label: 'Blocked start edge case',
      description: 'Start position is blocked so traversal exits immediately.',
      rows: 4,
      cols: 4,
      startR: 1,
      startC: 1,
      blockedInput: '1-1,2-2',
    },
  ],
  dfs: [
    {
      id: 'tree_like',
      label: 'Tree-like graph',
      description: 'Classic deep traversal with clear backtracking points.',
      nodeCount: 7,
      dfsStart: 0,
      edgesInput: '0-1,0-2,1-3,1-4,2-5,5-6',
    },
    {
      id: 'disconnected',
      label: 'Disconnected graph',
      description: 'Only the start component is visited.',
      nodeCount: 8,
      dfsStart: 3,
      edgesInput: '0-1,1-2,3-4,4-5,6-7',
    },
    {
      id: 'with_cycle',
      label: 'Graph with cycle',
      description: 'Cycle requires visited checks.',
      nodeCount: 6,
      dfsStart: 0,
      edgesInput: '0-1,1-2,2-3,3-1,3-4,4-5',
    },
  ],
  binary_search: [
    {
      id: 'target_found',
      label: 'Target found',
      description: 'Target exists and lower-bound lands on its index.',
      numsInput: '1,3,5,7,9,11',
      target: 7,
    },
    {
      id: 'lower_bound',
      label: 'Target missing',
      description: 'Target absent so result is insertion index.',
      numsInput: '1,3,5,7,9,11',
      target: 8,
    },
    {
      id: 'duplicates',
      label: 'Many duplicates',
      description: 'Lower-bound returns first matching duplicate index.',
      numsInput: '1,2,2,2,4,5',
      target: 2,
    },
  ],
  dp: [
    { id: 'small_n', label: 'Small n', description: 'Few subproblems with visible memo hits.', dpN: 5 },
    { id: 'medium_n', label: 'Medium n', description: 'Memoization effect is clearer.', dpN: 10 },
    { id: 'larger_n', label: 'Larger n', description: 'State count grows while each state is solved once.', dpN: 20 },
  ],
  prefix_difference: [
    {
      id: 'single_update',
      label: 'Single range update',
      description: 'Apply one diff update, rebuild array, and answer range sum.',
      numsInput: '1,2,3,4,5,6',
      updatesInput: '1-4-2',
      rangeL: 1,
      rangeR: 4,
    },
    {
      id: 'multi_update',
      label: 'Multiple updates',
      description: 'Batch several updates then query interval quickly via prefix.',
      numsInput: '2,2,2,2,2,2,2',
      updatesInput: '0-3-1,2-6-2,5-6-3',
      rangeL: 2,
      rangeR: 6,
    },
    {
      id: 'edge_update',
      label: 'Boundary update',
      description: 'Update touching final index to validate diff boundary handling.',
      numsInput: '5,1,0,3,2',
      updatesInput: '3-4-4',
      rangeL: 0,
      rangeR: 4,
    },
  ],
  intervals: [
    {
      id: 'mixed_overlap',
      label: 'Mixed overlap intervals',
      description: 'Some ranges overlap and should merge.',
      intervalsInput: '1-3,2-6,8-10,15-18',
    },
    {
      id: 'nested',
      label: 'Nested intervals',
      description: 'Fully nested intervals collapse to a wider one.',
      intervalsInput: '1-10,2-5,3-4,11-12',
    },
    {
      id: 'touching',
      label: 'Touching boundaries',
      description: 'Boundary-touching ranges test merge conditions.',
      intervalsInput: '1-2,2-3,3-4,7-8',
    },
  ],
  heap: [
    {
      id: 'topk_small',
      label: 'Top-k largest values',
      description: 'Keep only k strongest values with bounded min-heap.',
      numsInput: '9,4,7,1,5,3,8,6',
      heapK: 3,
    },
    {
      id: 'duplicates',
      label: 'Repeated priorities',
      description: 'Handles ties while preserving top-k size.',
      numsInput: '5,5,5,2,9,9,1,8',
      heapK: 4,
    },
    {
      id: 'k_one',
      label: 'k = 1',
      description: 'Heap tracks only the single best value.',
      numsInput: '2,11,4,8,6',
      heapK: 1,
    },
  ],
  monotonic_queue: [
    {
      id: 'window_max',
      label: 'Window maximum',
      description: 'Deque maintains descending values for fast max.',
      numsInput: '1,3,-1,-3,5,3,6,7',
      windowK: 3,
    },
    {
      id: 'flat_values',
      label: 'All equal values',
      description: 'Equal values test stable deque maintenance.',
      numsInput: '4,4,4,4,4',
      windowK: 2,
    },
    {
      id: 'large_window',
      label: 'Window near full length',
      description: 'Large k emphasizes out-of-window evictions.',
      numsInput: '2,9,1,7,5,3',
      windowK: 5,
    },
  ],
  topological_sort: [
    {
      id: 'simple_dag',
      label: 'Simple DAG',
      description: 'Dependency ordering with multiple valid outputs.',
      nodeCount: 6,
      edgesInput: '0-1,0-2,1-3,2-3,3-4,2-5',
    },
    {
      id: 'multi_sources',
      label: 'Multiple sources',
      description: 'Several zero-indegree starts enter queue initially.',
      nodeCount: 7,
      edgesInput: '0-3,1-3,2-4,3-5,4-5,5-6',
    },
    {
      id: 'cycle_case',
      label: 'Cycle detection case',
      description: 'Cycle causes incomplete topological order.',
      nodeCount: 4,
      edgesInput: '0-1,1-2,2-0,2-3',
    },
  ],
  union_find: [
    {
      id: 'connected_query',
      label: 'Connected query',
      description: 'Union edges then ask if two nodes share a component.',
      nodeCount: 8,
      edgesInput: '0-1,1-2,3-4,4-5,2-5,6-7',
      dsuA: 0,
      dsuB: 5,
    },
    {
      id: 'disconnected_query',
      label: 'Disconnected query',
      description: 'Query nodes in different components.',
      nodeCount: 8,
      edgesInput: '0-1,1-2,3-4,5-6',
      dsuA: 2,
      dsuB: 6,
    },
    {
      id: 'redundant_edges',
      label: 'Redundant edges',
      description: 'Repeated unions should be detected as already connected.',
      nodeCount: 5,
      edgesInput: '0-1,1-2,0-2,2-3,3-4',
      dsuA: 0,
      dsuB: 4,
    },
  ],
  backtracking: [
    {
      id: 'subset_found',
      label: 'Subset target found',
      description: 'Search path finds combination reaching target sum.',
      numsInput: '2,3,5,7,8',
      target: 10,
    },
    {
      id: 'subset_missing',
      label: 'No valid subset',
      description: 'Explores branches and backtracks to no-solution.',
      numsInput: '4,6,9',
      target: 5,
    },
    {
      id: 'pruning_useful',
      label: 'Pruning-heavy case',
      description: 'Many branches are cut once partial sum exceeds target.',
      numsInput: '1,2,3,4,5,6',
      target: 9,
    },
  ],
  trie: [
    {
      id: 'prefix_exists',
      label: 'Prefix exists',
      description: 'Inserted words share queried prefix.',
      wordsInput: 'apple,app,apply,ape,bat',
      triePrefix: 'app',
    },
    {
      id: 'prefix_missing',
      label: 'Prefix missing',
      description: 'Query prefix fails traversal before completion.',
      wordsInput: 'cat,car,carbon,dog',
      triePrefix: 'cap',
    },
    {
      id: 'single_letter',
      label: 'Single-letter prefix',
      description: 'Short prefixes should still resolve quickly.',
      wordsInput: 'zebra,zen,zero,zip',
      triePrefix: 'z',
    },
  ],
  greedy: [
    {
      id: 'activity_selection',
      label: 'Activity selection',
      description: 'Select maximum non-overlapping intervals greedily by end.',
      intervalsInput: '1-4,3-5,0-6,5-7,8-9,5-9',
    },
    {
      id: 'already_non_overlap',
      label: 'Already non-overlapping',
      description: 'All intervals can be selected.',
      intervalsInput: '1-2,3-4,5-6,7-8',
    },
    {
      id: 'dense_overlap',
      label: 'Dense overlap',
      description: 'Heavy overlap forces frequent skips.',
      intervalsInput: '1-10,2-3,3-4,4-5,6-7',
    },
  ],
  dijkstra: [
    {
      id: 'weighted_graph',
      label: 'Weighted undirected graph',
      description: 'Relax edges to compute shortest paths from source.',
      nodeCount: 6,
      weightedEdgesInput: '0-1-4,0-2-1,2-1-2,1-3-1,2-3-5,3-4-3,4-5-2',
      dijkstraStart: 0,
    },
    {
      id: 'unreachable_nodes',
      label: 'Unreachable nodes',
      description: 'Disconnected vertices should remain unreachable.',
      nodeCount: 7,
      weightedEdgesInput: '0-1-2,1-2-3,2-3-1,4-5-1',
      dijkstraStart: 0,
    },
    {
      id: 'zero_weight',
      label: 'Zero-weight edges',
      description: 'Zero-cost edges still satisfy non-negative requirement.',
      nodeCount: 5,
      weightedEdgesInput: '0-1-0,1-2-2,0-3-5,2-4-1,3-4-1',
      dijkstraStart: 0,
    },
  ],
};

export const DEFAULT_PATTERN_VISUALIZER_STATE: PatternVisualizerState = {
  patternKey: 'hash_set',
  numsInput: '2,7,11,7,3,11',
  target: 10,
  windowK: 5,
  stackInput: '({[]})[]',
  rows: 5,
  cols: 6,
  startR: 0,
  startC: 0,
  blockedInput: '1-1,1-2,3-4',
  nodeCount: 7,
  dfsStart: 0,
  edgesInput: '0-1,0-2,1-3,1-4,2-5,5-6',
  dpN: 10,
  intervalsInput: '1-3,2-6,8-10,15-18',
  updatesInput: '1-4-2',
  rangeL: 1,
  rangeR: 4,
  heapK: 3,
  dsuA: 0,
  dsuB: 1,
  wordsInput: 'apple,app,apply,ape,bat',
  triePrefix: 'app',
  weightedEdgesInput: '0-1-4,0-2-1,2-1-2,1-3-1,2-3-5,3-4-3,4-5-2',
  dijkstraStart: 0,
  activePresetId: PATTERN_PRESETS.hash_set[0]?.id ?? '',
};
